FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache \
    git \
    bash \
    ca-certificates

# hot reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]
