FROM golang:1.25-alpine

# Базовые утилиты (git нужен для go mod)
RUN apk add --no-cache git ca-certificates

# Рабочая директория
WORKDIR /app

# Копируем только go.mod / go.sum
COPY go.mod go.sum ./

# Скачиваем зависимости (кэшируем слой)
RUN go mod download

# Копируем весь проект
COPY . .

# Dev-окружение
ENV CGO_ENABLED=0
ENV GO_ENV=dev

# Контейнер ВСЕГДА стартует с нуля
CMD sh -c "go mod tidy && go run cmd/server/main.go"
