// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package auth

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (RegRequestDto) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*RegRequestDto) UnmarshalJSON([]byte) error        { return nil }
func (RegRequestDto) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*RegRequestDto) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RegRequestDto *RegRequestDto

func (TokenResp) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*TokenResp) UnmarshalJSON([]byte) error        { return nil }
func (TokenResp) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*TokenResp) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TokenResp *TokenResp
